More scripts; fixes
Signed-off-by: Vivek Rai <mail@raivivek.in>

diff --git a/bed2saf b/bed2saf
--- a/bed2saf
+++ b/bed2saf
@@ -1,9 +1,21 @@
 #! /bin/bash
-
-# TheParkerLab
+#
 # Vivek Rai
-# GPLv3
+# vivekrai@umich.edu
+# GPLv3, Parker Lab
+#
+# July 30, 2018
+#
 
-[[ -z $1 ]] && echo "Usage: PROG <BED-file>\nWrites to STDOUT." && exit
+[[ $1 == "-h" ]] \
+  && echo "Usage: bed2saf <BED-file>\nWrites to STDOUT." \
+  && exit
 
-awk 'BEGIN {NUM=0} {print (NUM+1)"\t"$0"\t-"; NUM=NUM+1}' $1 | sort -k2,2 -k3n
+[[ ! -e $1  && $1 ]] \
+  && echo "(bed2saf) ERROR: File does not exist." \
+  && exit 1
+
+echo "(bed2saf) INFO: Reading from STDIN" >&2
+
+#sort -k1,1 -k2,2n |
+cat $1 | awk -v OFS="\t" 'BEGIN {print "GeneID","Chr","Start","End","Strand"} { print "Peak_"NR,$1,$2+1,$3,"."}'
